# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordetail',
            name='ip_address',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
    ]
