# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160415_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=200)),
                ('sensor_location', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(max_length=200)),
                ('sensor_provider', models.CharField(max_length=200)),
                ('sensor_status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserDetails')),
            ],
        ),
    ]
