# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_availablesensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablesensordata',
            name='user',
        ),
    ]
